global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'kong'
    static_configs:
      - targets: ['bizflow-gateway:8001']

  - job_name: 'identity-svc'
    static_configs:
      - targets: ['identity-svc:4001'] # Dùng tên service trong docker-compose

  - job_name: 'product-svc'
    static_configs:
      - targets: ['product-svc:4002']

  - job_name: 'order-svc'
    static_configs:
      - targets: ['order-svc:4003']