global:
  scrape_interval: 5s # Nên để 5s để cập nhật nhanh hơn khi test

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'kong'
    static_configs:
      # 'bizflow-gateway' là container_name của Kong trong docker-compose
      - targets: ['bizflow-gateway:8001']

  - job_name: 'product-svc'
    static_configs:
      - targets: ['product-svc:4002'] # Nhớ đổi đúng port của service đó

  - job_name: 'order-svc'
    static_configs:
      - targets: ['order-svc:4003']